# Generated by Django 4.1.7 on 2024-08-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('MEMBER', 'MEMBER'), ('LIBRARY', 'LIBRARY')], default='MEMBER', max_length=24),
        ),
    ]
